CREATE TABLE IF NOT EXISTS delivery_readiness_checklists (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    generated_document_id BIGINT UNSIGNED NOT NULL,
    generated_document_version INT UNSIGNED NOT NULL,
    checklist_item VARCHAR(40) NOT NULL,
    is_checked TINYINT(1) NOT NULL DEFAULT 0,
    checked_by BIGINT UNSIGNED NULL,
    checked_at DATETIME NULL,
    reviewer_signed_by BIGINT UNSIGNED NULL,
    reviewer_signed_at DATETIME NULL,
    approver_signed_by BIGINT UNSIGNED NULL,
    approver_signed_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    notes TEXT NULL,
    created_at TIMESTAMP NULL,
    updated_at TIMESTAMP NULL,
    UNIQUE KEY uq_delivery_checklist_item (generated_document_id, generated_document_version, checklist_item),
    KEY idx_delivery_checklist_status (status, is_checked),
    KEY idx_delivery_checklist_doc (generated_document_id, generated_document_version),
    CONSTRAINT fk_delivery_checklist_doc FOREIGN KEY (generated_document_id) REFERENCES generated_documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_checklist_checked_by FOREIGN KEY (checked_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_checklist_reviewer_sign FOREIGN KEY (reviewer_signed_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_delivery_checklist_approver_sign FOREIGN KEY (approver_signed_by) REFERENCES users(id) ON DELETE SET NULL
);
